name: Deploy smartnest-website to EC2

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build React App
        run: |
          npm install
          npm run build

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t smartpet/smartnest-website:latest \
            --push .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull smartpet/smartnest-website:latest
            docker stop smartnest-website || true
            docker rm smartnest-website || true
            docker run -d \
              --name smartnest-website \
              -p 4174:80 \
              --restart always \
              smartpet/smartnest-website:latest
